<a href="https://colab.research.google.com/github/msolowes-star/DI-Bootcamp/blob/main/Week6DayExerciseXP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Exercise 1 — Array Creation

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Exercise 2 — Type Conversion

In [3]:
numbers = [3.14, 2.17, 0, 1, 2]

arr = np.array(numbers)
arr_int = arr.astype(int)

print(arr_int)

[3 2 0 1 2]


Exercise 3 — 3×3 Array

In [4]:
arr = np.arange(1, 10).reshape(3, 3)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 4 — Random 4×5 Array

In [5]:
arr = np.random.random((4, 5))

print(arr)

[[0.78490828 0.22570724 0.94424274 0.77035268 0.99288758]
 [0.34780784 0.79436226 0.71385029 0.75420905 0.99305211]
 [0.74817024 0.01087159 0.24652095 0.70849461 0.68021663]
 [0.11558584 0.68450733 0.8487355  0.70386137 0.17741362]]


Exercise 5 — Select the Second Row

In [6]:
arr = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

second_row = arr[1]

print(second_row)

[20 21 22 23 24]


Exercise 6 — Reverse an Array

In [7]:
arr = np.arange(10)

reversed_arr = arr[::-1]

print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


Exercise 7 — Identity Matrix

In [8]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercise 8 — Sum and Average

In [9]:
arr = np.arange(10)

total = np.sum(arr)
average = np.mean(arr)

print("Sum:", total)
print("Average:", average)

Sum: 45
Average: 4.5


Exercise 9 — Reshape 1–20

In [10]:
arr = np.arange(1, 21)

matrix = arr.reshape(4, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercise 10 — Select Odd Numbers

In [11]:
arr = np.arange(10)

odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
